# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fEwA706zqsbf39M9cJ6QCTm1nq_mOFSy
"""

x= 10

print (x)

x=110
y=20

x+y

x=10
type(x)

type (x)

x="sourav"
y="menon"

x+y

type (x)

x="10"
y="20"

x+y

x=input()

x

x=int(input())

x

x=int(input())
y=int(input())

x+y

x*y

x-y

x/y

x**y

p=int(input("enter initial principalbalance"))
r=int(input("enter annual intrest rate"))
t=int(input("enter the time"))
a=p*(1+r*t)

a

p=int(input("enter the principal amount"))
r=int(input("enter the intrest rate"))
n=int(input("enter the number of times intrest is compounded during the year"))
t=int(input('enterb the number of time'))
A=p*(1+r/n)**(n*t)
A

